---
# - name: Copy Certificates
#   copy:
#     src: ssl-certs/
#     dest: /etc/haproxy/ssl/


- name: Config Test and Deploy
  template:
    src: '{{ haproxy.config_file_name }}.cfg.j2'
    dest: /etc/haproxy/haproxy.cfg
    validate: haproxy -c -f %s
  notify: reload haproxy
